version: 0.1
phases: 
  install:
    commands:
      -aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-pipeline --output-template-file outSamTemplate.yaml
artifacts:
  type: zip
  files:
  - samTemplate.yaml
  - outputSamTemplate.yaml